SportClub/Models/Trainer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SportClub.Models
{
    public class Trainer
    {
      
        [Key]
        public int TrainerID { get; set; }

        [Display(Name = "Фото")]
        [DataType(DataType.ImageUrl,ErrorMessage = "Додайте фото")]
        public string Image { get; set; }

        [Display(Name = "Имя")]
        public string FName { get; set; }

        [Display(Name = "Фамилия")]
        public string LName { get; set; }

        [Display(Name = "Телефон")]
        [DataType(DataType.PhoneNumber)]
        public int Phone { get; set; }

        //[Display(Name = "Зарплата")]       
        //public decimal Salary { get; set; }

        [Display(Name = "Краткая информация")]
        public string Description { get; set; }

       
        [Display(Name = "Дата добавления")]
        [DataType(DataType.Date, ErrorMessage = "Введите дату")]
        public DateTime Data { get; set; }


        public virtual ICollection<Client> Client { get; set; }
    }
}

SportClub/Controllers/TrainerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportClub.Models;
using System.IO;

namespace SportClub.Controllers
{
    public class TrainerController : Controller
    {
        private ModelContext db = new ModelContext();

        //
        // GET: /Trainer/

        public ActionResult Index()
        {
           
            return View(db.Trainers.ToList());
        }

        //
        // GET: /Trainer/Details/5

        public ActionResult Details(int id = 0)
        {
            Trainer trainer = db.Trainers.Find(id);
            if (trainer == null)
            {
                return HttpNotFound();
            }
            return View(trainer);
        }

        //
        // GET: /Trainer/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Trainer/Create

        [HttpPost]
        [Authorize(Users = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase[] file1, Trainer trainer)
        {
            if (ModelState.IsValid)
            {
                foreach (var file in file1)
                {
                    if (file == null) continue;
                    UploadTrainerIco(trainer, file);

                    db.Trainers.Add(trainer);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            return View(trainer);
        }

        private void UploadTrainerIco(Trainer trainer, HttpPostedFileBase file)
        {
            //string fileName = null;
            var uploadDir = "/Content/avatarku/";
            var fileName = Path.GetFileName(file.FileName);
            var path = Path.Combine(Server.MapPath(uploadDir) + fileName);
            if (fileName != null) file.SaveAs(path);
            trainer.Image = "/Content/avatarku/" + fileName;
        }

        //
        // GET: /Trainer/Edit/5

        public ActionResult Edit(int? id )
        {
            Trainer trainer = db.Trainers.Find(id);
            if (trainer == null)
            {
                return HttpNotFound();
            }
            return View(trainer);
        }

        //
        // POST: /Trainer/Edit/5
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "admin")]
        public ActionResult Edit(Trainer trainer)
        {
            if (ModelState.IsValid)
            {

                db.Entry(trainer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(trainer);
        }

        //
        // GET: /Trainer/Delete/5
        [Authorize(Users = "admin")]
        public ActionResult Delete(int id = 0)
        {
            Trainer trainer = db.Trainers.Find(id);
            if (trainer == null)
            {
                return HttpNotFound();
            }
            return View(trainer);
        }

        //
        // POST: /Trainer/Delete/5
     
        [HttpPost, ActionName("Delete")]
        [Authorize(Users = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Trainer trainer = db.Trainers.Find(id);
            db.Trainers.Remove(trainer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

SportClub/Views/Trainer/Create.cshtml
@model SportClub.Models.Trainer

@{
    ViewBag.Title = "Добавить";
}

<h2>Добавить</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Create", "Trainer", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Trainer</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Image)
        </div>
        <div class="editor-field">
            <input type="file" name="file1" id="file1" accept="image/*" />
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FName)
            @Html.ValidationMessageFor(model => model.FName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LName)
            @Html.ValidationMessageFor(model => model.LName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Phone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Phone)
            @Html.ValidationMessageFor(model => model.Phone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Data)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Data)
            @Html.ValidationMessageFor(model => model.Data)
        </div>

        <p>
            <input type="submit" value="Сохранить" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Вернутся к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SportClub/Views/Trainer/Delete.cshtml
@model SportClub.Models.Trainer

@{
    ViewBag.Title = "Удаление";
}

<h2>Удаление</h2>

<h3>Вы уверены, что хотите продолжить удаление?</h3>
<fieldset>
    <legend>Trainer</legend>

    <div class="display-label">
        <b>@Html.DisplayNameFor(model => model.Image)</b>
    </div>
    <div class="display-field">
        <img alt="" width="80" height="80" src="@Url.Content(@Model.Image.ToString())"/>
    </div>

    <div class="display-label">
        <b>@Html.DisplayNameFor(model => model.FName)</b>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FName)
    </div>

    <div class="display-label">
        <b>@Html.DisplayNameFor(model => model.LName)</b>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LName)
    </div>

    <div class="display-label">
        <b>@Html.DisplayNameFor(model => model.Phone)</b>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Phone)
    </div>

    <div class="display-label">
        <b>@Html.DisplayNameFor(model => model.Description)</b>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
        <b>@Html.DisplayNameFor(model => model.Data)</b>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Data)
    </div>
</fieldset>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Удалить" />
        |
        @Html.ActionLink("Вернутся к списку", "Index")
    </p>
}

SportClub/Views/Trainer/Details.cshtml
@model SportClub.Models.Trainer

@{
    ViewBag.Title = "Детали";
}

<h2>Детали</h2>

<fieldset>
    <legend>Trainer</legend>

    <div class="display-label">
        <b>@Html.DisplayNameFor(model => model.Image)</b>
    </div>
    <div class="display-field">
        <img alt="" width="80" height="80" src="@Url.Content(@Model.Image.ToString())"/>
        @*@Html.DisplayFor(model => model.Image)*@
    </div>

    <div class="display-label">
        <b>@Html.DisplayNameFor(model => model.FName)</b>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FName)
    </div>

    <div class="display-label">
        <b>@Html.DisplayNameFor(model => model.LName)</b>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LName)
    </div>

    <div class="display-label">
        <b>@Html.DisplayNameFor(model => model.Phone)</b>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Phone)
    </div>

    <div class="display-label">
       <b> @Html.DisplayNameFor(model => model.Description)</b>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
        <b>@Html.DisplayNameFor(model => model.Data)</b>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Data)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.TrainerID }) |
    @Html.ActionLink("Вернутся к списку", "Index")
</p>

SportClub/Views/Trainer/Edit.cshtml
@model SportClub.Models.Trainer

@{
    ViewBag.Title = "Редактировать";
}

<h2>Редактировать</h2>
<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Trainer</legend>

        @Html.HiddenFor(model => model.TrainerID)

          <div class="editor-label">
            @Html.LabelFor(model => model.Image)
        </div>
        <div class="editor-label">
            <img alt="" width="200" height="200" src="@Url.Content(@Model.Image.ToString())"/>
        </div>
        <div class="editor-field">
            <input type="file" name="file1" id="file1" accept="image/*"  />
     
            @*@Html.EditorFor(model => model.Image)*@
            @Html.ValidationMessageFor(model => model.Image)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FName)
            @Html.ValidationMessageFor(model => model.FName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LName)
            @Html.ValidationMessageFor(model => model.LName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Phone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Phone)
            @Html.ValidationMessageFor(model => model.Phone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Data)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Data)
            @Html.ValidationMessageFor(model => model.Data)
        </div>

        <p>
            <input type="submit" value="Сохраниить" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Вернутся к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SportClub/Views/Trainer/Index.cshtml
@model IEnumerable<SportClub.Models.Trainer>

@{
    ViewBag.Title = "Тренеры";
}
<h2>Список тренеров</h2>

<p>
    @Html.ActionLink("Добавить тренера", "Create")
</p>
@*@using (Html.BeginForm("Index", "Student", FormMethod.Get))
{
    *@<p>
        Поиск по имени: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Поиск" />
    </p>
@*}*@
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Data)
        </th>
        <th></th>
    </tr>
    @* <script type="text/javascript">
        function openImageWindow(src) {
            var image = new Image();
            image.src = src;
            var width = image.width;
            var height = image.height;
            window.open(src, "Image", "width=" + width + ",height=" + height);
        }
    </script>*@

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <div style="text-align: center;">
                    <a href="#image">
                        <img title="@item.LName @item.FName" src="@item.Image" width="120" height="120" alt="@item.LName @item.FName" /></a>
                </div>

                <a href="#x" class="overlay" id="image"></a>
                <div class="popup">
                    <img class="is-image" title="@item.LName" src="@item.Image" alt="@item.LName" />
                    <a class="close" title="Закрыть" href="#close"></a>
                </div>
                @*<img alt="" width="120" height="120" onclick="openImageWindow(this.src)" title="@item.LName @item.FName" src="@item.Image"/>*@



            </td>

            <td>
                @Html.DisplayFor(modelItem => item.FName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data)
            </td>
            <td>
                <a href="@Url.Action("Edit", "Trainer", new { id = item.TrainerID })">
                    <img style="width: 30px; height: 30px;" alt="Редактировать" title="Редактировать" src="~/Content/edit.png" /></a>
                <a href="@Url.Action("Details", "Trainer", new { id = item.TrainerID })">
                    <img style="width: 30px; height: 30px;" alt="Детали" title="Детали" src="~/Content/details.png" /></a>
                <a href="@Url.Action("Delete", "Trainer", new { id = item.TrainerID })">
                    <img style="width: 30px; height: 30px;" alt="Удалить" title="Удалить" src="~/Content/delete.png" /></a>


                @*@Html.ActionLink("Редактировать", "Edit", new { id=item.TrainerID }) |
            @Html.ActionLink("Детали", "Details", new { id=item.TrainerID }) |
            @Html.ActionLink("Удалить", "Delete", new { id=item.TrainerID })*@
            </td>
        </tr>
    }

</table>