SportClub/Models/UploadFile.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SportClub.Models
{
    public class UploadFile
    {
        [Key]
        [Display(Name = "№")]
        public int UploadFileID { get; set; }
        [Display(Name = "Шлях до файлу")]
        public string PatchToFile { get; set; }
    }
}

SportClub/Controllers/UploadFileController.cs
using SportClub.Models;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportClub.Controllers
{
    public class UploadFileController : Controller
    {
        private ModelContext db = new ModelContext();
        //
        // GET: /UploadFile/

        public ActionResult Index()
        {
            return View(db.UploadFile.ToList());
        }

        public ActionResult ADDFile()
        {
           
            return View();
        }

        [HttpPost]
        public ActionResult ADDFile(HttpPostedFileBase[] fileUpload,UploadFile UpFile)
        {
            if (ModelState.IsValid)
            {
                foreach (var file in fileUpload)
                {
                    if (file == null) continue;
                    var uploadDir = "/Content/UploadFile/";
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath(uploadDir) + fileName);
                    if (fileName != null) file.SaveAs(path);
                    UpFile.PatchToFile = "/Content/UploadFile/" + fileName;
                    db.UploadFile.Add(UpFile);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(UpFile);
        }
    }
}

SportClub/Views/UploadFile/ADDFile.cshtml
@model SportClub.Models.UploadFile

@{
    ViewBag.Title = "ADDFile";
}

<h2>ADDFile</h2>

@using (Html.BeginForm("ADDFile", "UploadFile", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>File</legend>
        @Html.LabelFor(model => model.PatchToFile)
        <input type="file" name="file1" id="file1" accept="image/*" />
    </fieldset>
}

SportClub/Views/UploadFile/Index.cshtml
@model IEnumerable<SportClub.Models.UploadFile>

@{
    ViewBag.Title = "Index";
}
@Html.ActionLink("Create New", "ADDFile")

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UploadFileID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PatchToFile)
        </th>
        <th>
    </tr>

    @foreach (var item in Model) {
    <tr>
        <td>
            <img alt="" width="80" height="80" src="@item"/>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UploadFileID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PatchToFile)
        </td>
        </tr>
    }       
        </table>

        